# Generated by Django 3.1.1 on 2020-09-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0002_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sales_channel',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
