# Generated by Django 3.1.1 on 2020-09-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0003_order_sales_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sales_channel',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='unit_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='unit_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='units_sold',
            field=models.FloatField(),
        ),
    ]
