# Generated by Django 3.1.1 on 2020-09-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0004_auto_20200924_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='units_sold',
            field=models.IntegerField(),
        ),
    ]
