# Generated by Django 3.1.1 on 2021-01-25 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0006_auto_20200924_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('amount', models.IntegerField(default=0)),
                ('amount_in_words', models.CharField(default=0, max_length=60)),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='CSV',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='location',
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='receipt',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesapp.item'),
        ),
    ]
