# Generated by Django 3.1.1 on 2021-01-25 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0007_auto_20210125_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20, unique=True)),
                ('cost', models.IntegerField()),
                ('price', models.IntegerField()),
                ('number_available', models.IntegerField()),
                ('initial_quantity', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='receipt',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesapp.stock'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
