# Generated by Django 3.1.1 on 2021-01-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0009_auto_20210125_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
