# Generated by Django 3.1.1 on 2021-01-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0011_auto_20210126_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='cash_or_cheque',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque')], default='Cash', max_length=7),
            preserve_default=False,
        ),
    ]
