# Generated by Django 3.1.1 on 2021-01-28 12:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0012_receipt_cash_or_cheque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20, unique=True)),
                ('cost', models.IntegerField()),
                ('price', models.IntegerField()),
                ('number_in_stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrackSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.datetime(2021, 1, 28, 12, 0, 39, 525867))),
                ('end_date', models.DateField(default=datetime.datetime(2021, 1, 28, 12, 0, 39, 525883))),
            ],
        ),
        migrations.CreateModel(
            name='ItemStocking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesapp.item')),
            ],
        ),
        migrations.AlterField(
            model_name='receipt',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesapp.item'),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
