# Generated by Django 3.1.1 on 2021-01-28 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0014_auto_20210128_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracksetting',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tracksetting',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
