# Generated by Django 3.1.1 on 2021-01-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0015_auto_20210128_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
