# Generated by Django 3.1.1 on 2021-01-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0016_auto_20210128_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
