# Generated by Django 3.1.1 on 2021-02-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0017_auto_20210128_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='number_in_stock',
            field=models.IntegerField(default=0),
        ),
    ]
